# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: babf7ba270883daf51ddfd07c98a26c40c192353b6009e669661b819ba017ed13ee50c3e8f898a5a531fae9318029831422872372b7e6780d10e04d31beed693

test:
  secret_key_base: d0609c019810f49d0c160ba6a8f197384a03bfb9927045099c6d1f8390e9a74df7098a147c6d79b0807f46a7b42b7c83609eb15fdf96ddb85ec0fd10327777cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
